version: '3.8'
services:
  postgres:
    image: postgres:12.3
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_USER=admin
      - POSTGRES_PASSWORD=12345
      - POSTGRES_DB=hotel_db
  hotelland:
    build:
      context: .
      dockerfile: Dockerfile
    image: hotelland