spring:
  jpa:
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        format_sql: true
    generate-dll: true
    open-in-view: false
    hibernate:
      ddl-auto: update
    show-sql: true
  datasource:
    url: jdbc:postgresql://localhost:5432/hotel_db
    username: admin
    password: 12345
  hikari:
    schema: app_schema
    connection-init-sql: CREATE SCHEMA IF NOT EXISTS hotel_schema
    connection-timeout: 10000